### PR TITLE
Properties init and cache

### LINKED ISSUE #655: Properties.<module> wrongly overrides defaults
When `Properties.<module>` has its own keys, we expect that the contents are merged with defaults.

For example, when config is as follows:
```php
'Properties' => [
        'users' => [
            'fastCreate' => [
                'required' => ['status', 'username'],
                'all' => ['status', 'username', 'email'],
            ],
    ],
],
```
At runtime (`PropertiesComponent::initialize()`) we expect a merged with defaults "properties" config, like:
```php
'Properties' => [
        'users' => [
            '_keep' => [
                // defaults ...
            ],
            'fastCreate' => [
                'required' => ['status', 'username'],
                'all' => ['status', 'username', 'email'],
            ],
            'index' => [
                // defaults ...
            ],
            'view' => [
                // defaults ...
            ],
    ],
],
```

### PR DESCRIPTION
**Pull request by didoda**
This fixes #655 

Bonus: caching the properties, so that the properties init is done just once, and not every time the component is used.

### CODE REVIEW

File: src/Controller/Component/PropertiesComponent.php [hunk 1]
```diff
@@ -84,12 +86,45 @@ class PropertiesComponent extends Component
...
     }
 
+    /**
+     * Init properties
+     *
+     * @return void
+     */
+    protected function init(): void
+    {
+        $cacheKey = CacheTools::cacheKey('properties');
```
Comment (stefanorosanelli) [inline src/Controller/Component/PropertiesComponent.php:101]: Overall ok, `Cache` usage seems like overkill in order to avoid these array manipulations

**Review by stefanorosanelli — APPROVED** [review]

File: src/Controller/Component/PropertiesComponent.php (hunk 1 above)
Comment (didoda) [reply src/Controller/Component/PropertiesComponent.php:101]: well... it's called 4 times on every content "view". not a lot, but I'd say better avoiding any unrequired repetition

**Review by nicolocarpignoli — APPROVED** [review]
