### PR TITLE
#43 feat: show response error in be-object-form component

### LINKED ISSUE #43: API error response not displayed
In case of API operations like trying to delete `role` 1, we get a `403` error response from API but nothing is displayed to user.

To reproduce: 
 - https://manager-heroku.bedita.net/roles/1 
 - press `Trash`
 - nothing happens

### PR DESCRIPTION
**Pull request by didoda**
This fixes #43 
It provides an `alert` message on error during `DELETE` or `POST` in `be-object-form`.
Todo: use something better than `alert`, i.e. a proper feedback message window

### CODE REVIEW

File: src/components/be-object-form/be-object-form.js [hunk 1]
```diff
@@ -128,6 +137,19 @@ export class BEObjectForm extends mix(Component).with(ModelMixin, FormatterMixin
...
+
+    /**
+     * Show response feedback
+     * 
+     * @todo use a better method than `alert` to show feedback (maybe a factory? this method could be moved elsewhere)
+     * @param object response 
+     */
+    showResponse(response) {
+        if (response.error) { // on error, show message
+            alert(response.error.title);
```
Comment (stefanorosanelli) [inline src/components/be-object-form/be-object-form.js]: what about the same notification system used on successful save operations?

something like:
```
            this.factory('notifications').notify({ body: response.error.title, type: 'error', timeout: 6000 });
```

Comment (didoda) [reply src/components/be-object-form/be-object-form.js]: Good point :) I'll apply a patch soon
